### PR TITLE
Add Manifest

### PR DESCRIPTION
**Pull request by airon90**
See https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen#Manifest
"start_url" should be added

### CODE REVIEW

**Comment by airon90** [comment]
> Any insight why you think it should be added?

This PR is about adding the basis to transform a simple website into a webapp, that can be easily installed on one's phone instead of opening browser and navigate into the website and moreover provides the same user experience advantages as native apps, without coding for Android, iOS and other minor OSes.

You can also add [more data](https://developer.mozilla.org/en-US/docs/Web/Manifest), e.g. categories or screenshot, to add metadata to your website/webapp. Last step will be to add offline support with a [service worker](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers).

I hope I clarify why this file (and the code added to index file) is useful. If you have any request please comment here

**Comment by sylhare** [comment]
Ok, I'll go with it and try it

**Comment by airon90** [comment]
There is a problem:
Either you didn't add ```start_url``` parameter (see below) or [this](https://github.com/sylhare/Truth-or-Dare/blob/master/index.html#L14) doesn't link properly.
Moreover, last comma should be removed.

```start_url```: Provides a path to the asset that should be loaded when the added-to-Home screen app is launched. Note that this has to be a relative URL pointing to the site index, relative to the url of the manifest. Also, be aware that Chrome requires this before it will display the install banner, whereas Firefox doesn't require it for showing the home-with-a-plus icon.

**Comment by sylhare** [comment]
Allo, the site is hosted on github. So maybe some of the feature are not there. I didn't make any change out of pull request.

I can always revert the change, or you can rework it if you want. 😉

**Comment by airon90** [comment]
I know what is happening!
If you visit https://sylhare.github.io/Truth-or-Dare/ it visit the index.html in /src folder.
Please, could you move the webmanifest file in src folder and make the changes I made to index.html to the one in /src folder?

**Comment by airon90** [comment]
Then, I suppose you can remove [this index.html](https://github.com/sylhare/Truth-or-Dare/blob/master/index.html)

**Comment by sylhare** [comment]
I need this one since it is hosted on github it needs to have an index.html at the root of the project. That's a very lazy way to do it. But I also wanted at the time to have everything in the source file working, in case somebody wanted to use it locally.

**Comment by sylhare** [comment]
> I know what is happening!
> If you visit https://sylhare.github.io/Truth-or-Dare/ it visit the index.html in /src folder.
> Please, could you move the webmanifest file in src folder and make the changes I made to index.html to the one in /src folder?

I am all willing to accept that pull request if you want to create it 😄

**Pull request merged**
