### PR TITLE
Create manifest.webmanifest

### PR DESCRIPTION
**Pull request by airon90**

### CODE REVIEW

**Comment by sylhare** [comment]
Allo Instead of creating a new one, can't we use the previous one? Or delete the previous one.
I would prefer not to duplicate files.

**Comment by airon90** [comment]
I don't know git, I just use GitHub commands and I don't know how to move files.
I didn't touch neither old webmanifest file nor old index.html because I would like to know if now it will work. If so I will work on those files

**Comment by sylhare** [comment]
Try downloading the repo (`git clone`) and running that locally and see if that works ;)
Then you can do your changes and push. Github has a lot of documentation on how to use git, check it out it will be very useful! 😃

**Comment by airon90** [comment]
Why did you close it without merging my commit?

**Comment by sylhare** [comment]
Because I did it myself 😉

**Pull request closed without merging**
